version: "2"
services:
    core:
        image: eyeseetea/dhis2-core:2.32
        labels:
            - "com.eyeseetea.image-name=eyeseetea/dhis2-data:2.32-samaritans"
        volumes:
            - home:/DHIS2_home
            - ./config:/config
            - data:/data
        environment:
            CATALINA_OPTS: "-Dcontext.path="
            JAVA_OPTS: "-Xmx7500m -Xms4000m"
            LOAD_FROM_DATA: "yes"
        entrypoint: sh /config/dhis2-core-entrypoint.sh
        command: sh /config/dhis2-core-start.sh
        depends_on:
            - "db"
    db:
        image: "mdillon/postgis:10-alpine"
        labels:
            - "com.eyeseetea.image-name=eyeseetea/dhis2-data:2.32-samaritans"
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: dhis2
            POSTGRES_USER: dhis
            POSTGRES_PASSWORD: dhis
        command: "postgres -c max_locks_per_transaction=100"
    gateway:
        image: "jwilder/nginx-proxy:alpine"
        labels:
            - "com.eyeseetea.image-name=eyeseetea/dhis2-data:2.32-samaritans"
        ports:
            - "8090:80"
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./config/50x.html:/usr/share/nginx/html/50x.html:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
        depends_on:
            - "core"
    data:
        image: "eyeseetea/dhis2-data:2.32-samaritans"
        environment:
            VOLUME: /volume-data
            LOAD_FROM_DATA: "yes"
        volumes:
            - data:/volume-data

volumes:
    pgdata:
        driver: local
    home:
        driver: local
    data:
        driver: local
